### PR TITLE
Update cleaning of dataset

### LINKED ISSUE #33: Normalizing data
Are we planning to normalize data for questions with open answers?
For example, 5. About how much money do you expect to earn per year at your first developer job (in US Dollars)?

Avg.$ = $53K per year, but some answers have $800K and more.
If set the upper bound to $200K per year, then avg.$ = $48K annually

Also some answers with "K" ($70K), and some are with full numbers ($70000)
And some answers are too small to be annually, but good enough to be monthly. In many countries people never use annual salaries, but monthly. So lots of people was probably confused and wrote their monthly expectations.

I did some normalizing, but in the end the average expectation didn't change a lot.
Original avg.$ = $53K/year VS $52K/year for normalized data.

Normalizing is a good practice, but it didn't change much in this example, so are we planning to do it? If yes, then we need to agree on conditions.

[2016FCC_moneyAnnual_v.0.2.xlsx](https://github.com/FreeCodeCamp/2016-new-coder-survey/files/251904/2016FCC_moneyAnnual_v.0.2.xlsx)

### PR DESCRIPTION
**Pull request by erictleung**
- **Change commute times >300 minutes to NA**
- **Change minimum mortgage to $1000 and maximum mortgage to $1000000**
- Move data dictionary into `clean-data/` directory
- **Change minimum student debt to $1000 and maximum debt to $500000**
- Add changelog to clean data README
- Remove missing data encoding information in README
- Add example exploration in clean data README
- Add figure of distribution of ages in dataset
- ~~**Change naming of some columns that were originally extracted from "Other"
  columns in the dataset to reflect columns were derived, rather than
  originally being there**~~
- **Clean data for children to make sure number of children and yes/no answer to
  having children is consistent**
- Fix spelling mistake in `IsReceiveDisabilitiesBenefits` (original:
  IsReceiveDiabilitiesBenefits)
- Use `ungroup()` command in `time_diff_check` because of `dplyr` version
  changes
- Separate polishing steps for podcasts, resources, and so on to make it easier
  to see what is being polished
- Update survey data dictionary description with details on the two datasets
  and parts of the survey
- Update survey data
- Update version numbers for R packages

cc/ @evaristoc @SamAI-Software @QuincyLarson 

Close #33

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@erictleung I am unfamiliar with R so I don't feel qualified to QA this, but all of these changes you described sound sane :)

**Comment by SamAI-Software** [comment]
The issues might be because some people already did their analyses, so changing variable names will break their code. Mine, too.
I understand the reasons why Eric changed names and fixed typos, but it might be too late for that.

**Comment by erictleung** [comment]
Right, I understand that I've changed those variables names and it will break some people's code. @evaristoc and I discussed the reason for renaming the variable names with `Other` in them. And I agree, it might be too late at this point. 

I guess it is not _too_ urgent that those variable names be changed. I can revert them back and just make a note of it in the `README` file. 

The most important part of the change is the normalization part to address issue #33.

**Comment by SamAI-Software** [comment]
> The most important part of the change is the normalization part to address issue #33.

This part seems to be fine.

If you revert the old variable names and add a note into `README`, then we should be good to go.

**Comment by erictleung** [comment]
@SamAI-Software awesome, I'll try to get to it later tonight.

**Comment by erictleung** [comment]
@SamAI-Software updated my PR!

I reverted the major change of adding `Other` into the variables names. I did, however, keep the variable change for `IsReceiveDisabilitiesBenefits` as the original `IsReceiveDiabilitiesBenefits` has a typo.

Feel free to pull down my PR and QA check the dataset. Let me know if there's anything else of concern 😃

**Comment by SamAI-Software** [comment]
LGTM

**Comment by thanhlan1912** [comment]
https://m.facebook.com/profile.php?id=100005562164845

**Pull request merged**
