### PR TITLE
Added missing variables

### PR DESCRIPTION
**Pull request by M0nica**
Some of the variables in the `survey-data-dictionary.md` were missing, so I added them in. The variable section for each question (Variable) is still the column name in the cleaned up dataset. I am only trying to commit https://github.com/FreeCodeCamp/2016-new-coder-survey/commit/0789b4f5c2db8919a9220ec7847ed29986e2bde6. Please ignore other commits.

### CODE REVIEW

**Comment by M0nica** [comment]
I am only trying to merge: commit 0789b4f5c2db8919a9220ec7847ed29986e2bde6 

https://github.com/FreeCodeCamp/2016-new-coder-survey/pull/49/commits/0789b4f5c2db8919a9220ec7847ed29986e2bde6

**Comment by SamAI-Software** [comment]
@M0nica :cool: thanks for adding variables with 0789b4f!

A few small bugs:
- `School Major` = `SchoolMajor`
- Second `CountryLive` = `CityPopulation`

For visualizations you can also check out issues #40 & #41 and add them there.

**Comment by M0nica** [comment]
Thanks @SamAI-Software I incorporated those two changes here: in this commit: https://github.com/M0nica/2016-new-coder-survey/commit/0e27972421aca8b17cf0559213501e397189ace9

**Comment by QuincyLarson** [comment]
Hi @M0nica we are eager to merge your changes. However, there are conflicts and it seems a lot of other changes have polluted your pull request. If all of your changes are to a single file, could you:
- copy that file's changes
- pull the master branch
- create a new branch off of it 
- create a new commit (paste your updated code into master's version of the file
- create a new pull request with just that change?

Thanks for your patience and your help!

**Pull request closed without merging**
