### PR TITLE
Add map preloader

### PR DESCRIPTION
**Pull request by SamAI-Software**
[**Website preview is here**](https://samai-software.github.io/2016-new-coder-survey/#Podcast)
- [x] Add map preloader
  - to fix the DOM for proper anchor when share links with ID like: https://freecodecamp.github.io/2016-new-coder-survey/#Podcast
- [x] Delete footnote _20 responses_ for **Location** map

---

@krisgesling, it's a quick fix, so may be later you can make preloader better and more flexible to changes. The idea is to set height to all DOM elements before the user is anchored to a topic from url ID (.../#Podcast).
You don't set height for the map's legend in the code, so I basically set it to 70px, which might be a problem if somebody will change the legend's content or CSS for it and will forget to adjust 70px in map.js.

### CODE REVIEW

**Comment by krisgesling** [comment]
Nice work, thanks!

Just in terms of the wording change, I don't think it's correct grammar to say the 'new coders are ethnic minority'. It makes it sound like 'new coders' is a type of 'ethnic minority'. I guess the simplest wording I can think of is 'new coders who are from an ethnic minority in their country'.

I may change the jQuery to d3 or vanilla js and call the preloader from within maps.js just to remove dependencies for future projects. Doesn't matter so much in this context given the rest of the page uses jQuery already.

**Comment by SamAI-Software** [comment]
> I don't think it's correct grammar to say the 'Proportion of new coders who are ethnic minority in their country.'

Otherwise it won't fit on the small screens :) It's the easiest way. Of course, there are other solutions through CSS, but they are not so easy, because we have 4 maps in the same container, which should keep the same height.
You know your code better, so feel free to fix that, but make sure that there will be no overlapping on 320px screens.

**Comment by krisgesling** [comment]
"Proportion of new coders who are from an ethnic minority in their
country." seems to work down to 300px screen width.

**Comment by krisgesling** [comment]
There's also two console.logs left in barcharts.js, not sure if you want to remove those before it goes live too.

**Comment by SamAI-Software** [comment]
@krisgesling done :+1:

**Comment by QuincyLarson** [comment]
Excellent work!

**Pull request merged**
